---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/quakes":
    get:
      summary: list earthquakes
      tags:
      - Earthquakes
      responses:
        '200':
          description: successful
    post:
      summary: create earthquake
      tags:
      - Earthquakes
      responses:
        '200':
          description: successful
  "/api/v1/quakes/new":
    get:
      summary: new earthquake
      tags:
      - Earthquakes
      responses:
        '200':
          description: successful
  "/api/v1/quakes/{id}/edit":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: edit earthquake
      tags:
      - Earthquakes
      responses:
        '200':
          description: successful
  "/api/v1/quakes/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show earthquake
      tags:
      - Earthquakes
      responses:
        '200':
          description: successful
    patch:
      summary: update earthquake
      tags:
      - Earthquakes
      responses:
        '200':
          description: successful
    put:
      summary: update earthquake
      tags:
      - Earthquakes
      responses:
        '200':
          description: successful
    delete:
      summary: delete earthquake
      tags:
      - Earthquakes
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: my-earthquake-api-v1.fly.dev
